# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UT0tSfm2YgNdSYbiCLGsnsMC4qf3SA8Z

# **1. Import Library**
"""

import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

"""# **2. Load dataset hasil preprocessing**"""

df = pd.read_csv("iris_preprocessed.csv")

X = df.drop("Species", axis=1)
y = df["Species"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""# **3. Mengaktifksn autolog MLflow**"""

mlflow.sklearn.autolog()

with mlflow.start_run():
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print("Accuracy:", acc)

import joblib
import os

os.makedirs("artifacts", exist_ok=True)
joblib.dump(model, "artifacts/iris_model.pkl")
print("Model saved to artifacts/iris_model.pkl")
